# Generated by Django 4.2.7 on 2023-11-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("musicians", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time_start",
                    models.DateTimeField(
                        blank=True, help_text="дата-время начала", null=True
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Submitted"),
                            (2, "Considered"),
                            (3, "Confirmed"),
                            (4, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="musicians.musician",
                    ),
                ),
            ],
        ),
    ]
