# Generated by Django 4.2.7 on 2023-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("genre", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("date_of_registration", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
